FROM alexellis2/nginx-arm:v6


ENV TZ Australia/Sydney

RUN test -e /etc/nginx/nginx.conf && \
	mkdir -p /var/nginx/proxy_temp

COPY docker/nginx/nginx.conf /etc/nginx/nginx.conf
COPY docker/nginx/http.conf /etc/nginx/conf.d/http.conf
COPY docker/nginx/proxy.conf /etc/nginx/conf.d/proxy.conf
COPY docker/nginx/wordpress.conf /etc/nginx/conf.d/wordpress.conf
COPY docker/nginx/fastcgi.inc /etc/nginx/conf.d/fastcgi.inc

COPY web /var/www/html
COPY config /var/www/html/config
